name: Train DYNAMO on GPU

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train Phase 1
      run: |
        python train.py --config config_working.yaml --phase 1 --device cpu
    
    - name: Upload checkpoints
      uses: actions/upload-artifact@v3
      with:
        name: dynamo-checkpoints
        path: checkpoints/
